// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiyinmqcwsgnfkhuponu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeWlubXFjd3NnbmZraHVwb251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTQ1NzIsImV4cCI6MjA1OTkzMDU3Mn0.MvG9gx8ShxIOOIhayS3CZvQ5UZ3S0FvhpyYHX608lw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);